project_id = "tmwetaohthghggimcjxb"

[functions.generate-job-invoices]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.api]
verify_jwt = false

[functions.bill-import]
verify_jwt = false
